FROM node:22 as build
WORKDIR /app
COPY package*.json ./
RUN npm install --force
RUN npm install -g @angular/cli --force
COPY . .
ARG API_URI
RUN sed -i "s|http://localhost:8000|${API_URI}|g" /app/src/app/environment.ts
RUN ng build --configuration=production
FROM nginx:latest
COPY --from=build /app/dist/marlene /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["sh", "-c", "nginx -g 'daemon off;' && nginx -s reload"]